<?php

declare(strict_types = 1);

namespace Tests\Feature;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Str;
use PHPUnit\Framework\Attributes\CoversClass;
use SineMacula\Laravel\Authorization\AuthorizationServiceProvider;
use SineMacula\Laravel\Authorization\Contracts\PrincipalResolver;
use SineMacula\Laravel\Authorization\Models\Permission;
use SineMacula\Laravel\Authorization\Models\Role;
use SineMacula\Laravel\Authorization\Registrars\BladeDirectiveRegistrar;
use SineMacula\Laravel\Authorization\Registrars\EventListenerRegistrar;
use SineMacula\Laravel\Authorization\Registrars\GateRegistrar;
use SineMacula\Laravel\Authorization\Support\BladeHelpers;
use Tests\Feature\Stubs\StubIdentity;
use Tests\TestCase;

/**
 * Feature coverage for the shipped Blade directives (issue #34).
 *
 * The service provider registers a `Blade::if`-backed set of
 * directives (`@role`, `@permission`, `@anyrole`, `@allroles`,
 * `@anypermission`, `@allpermissions`, plus Spatie-compat aliases
 * `@hasrole`, `@hasanyrole`, `@hasallroles`) and a companion
 * `@endunlessrole` directive. Every directive resolves the current
 * principal through `PrincipalResolver` and delegates to
 * `BladeHelpers`.
 *
 * Test templates keep whitespace either side of each directive.
 * Blade's statement regex is `\B@…`, which requires a non-word
 * boundary before the `@`; a literal token like `yes@endrole`
 * leaves the closing directive unmatched and produces a PHP
 * parse error. The assertions `trim()` the rendered output so
 * the leading/trailing whitespace does not mask the content.
 *
 * @author      Ben Carey <bdmc@sinemacula.co.uk>
 * @copyright   2026 Sine Macula Limited
 *
 * @internal
 *
 * @SuppressWarnings("php:S1192")
 */
#[CoversClass(BladeHelpers::class)]
#[CoversClass(AuthorizationServiceProvider::class)]
#[CoversClass(GateRegistrar::class)]
#[CoversClass(BladeDirectiveRegistrar::class)]
#[CoversClass(EventListenerRegistrar::class)]
final class BladeDirectivesTest extends TestCase
{
    /**
     * Permission string reused across multiple directive
     * assertions. Deduplicated to a constant so the same literal
     * does not leak into many call sites.
     *
     * @var string
     */
    private const string PERMISSION = 'posts:edit';

    /**
     * `@role` with a single role string admits a principal
     * holding that role.
     *
     * @return void
     */
    public function testRoleDirectiveAdmitsWhenRoleHeld(): void
    {
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'admin',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('admin');

        $this->actAs($user);

        $output = $this->render('@role(\'admin\') yes @endrole');

        self::assertSame('yes', $output);
    }

    /**
     * `@role` emits nothing when the principal lacks the role.
     *
     * @return void
     */
    public function testRoleDirectiveRendersEmptyWhenRoleMissing(): void
    {
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'admin',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);

        $this->actAs($user);

        $output = $this->render('@role(\'admin\') yes @endrole');

        self::assertSame('', $output);
    }

    /**
     * Anonymous principals evaluate every directive to false —
     * the view layer stays fail-closed.
     *
     * @return void
     */
    public function testRoleDirectiveEvaluatesFalseForAnonymousPrincipal(): void
    {
        $this->actAs(null);

        $output = $this->render('@role(\'admin\') admitted @endrole');

        self::assertSame('', $output);
    }

    /**
     * `@elserole` is auto-generated by `Blade::if` and fires when
     * the `@role` predicate fails.
     *
     * @return void
     */
    public function testRoleElseBranchFiresWhenRoleMissing(): void
    {
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'admin',
            'guard_name' => 'web',
        ]);
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'editor',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('editor');

        $this->actAs($user);

        $output = $this->render('@role(\'admin\') one @elserole(\'editor\') two @endrole');

        self::assertSame('two', $output);
    }

    /**
     * `@anyrole` with an array resolves to OR semantics.
     *
     * @return void
     */
    public function testAnyRoleDirectiveAdmitsOnAnyMatch(): void
    {
        Role::create(['id' => (string) Str::uuid(), 'name' => 'admin', 'guard_name' => 'web']);
        Role::create(['id' => (string) Str::uuid(), 'name' => 'editor', 'guard_name' => 'web']);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('editor');

        $this->actAs($user);

        $output = $this->render('@anyrole([\'admin\', \'editor\']) match @endanyrole');

        self::assertSame('match', $output);
    }

    /**
     * `@allroles` requires every role to be held.
     *
     * @return void
     */
    public function testAllRolesDirectiveRequiresEveryRole(): void
    {
        Role::create(['id' => (string) Str::uuid(), 'name' => 'admin', 'guard_name' => 'web']);
        Role::create(['id' => (string) Str::uuid(), 'name' => 'oncall', 'guard_name' => 'web']);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('admin');

        $this->actAs($user);

        $partial = $this->render('@allroles([\'admin\', \'oncall\']) all @endallroles');
        self::assertSame('', $partial);

        $user->assignRole('oncall');

        $full = $this->render('@allroles([\'admin\', \'oncall\']) all @endallroles');
        self::assertSame('all', $full);
    }

    /**
     * An empty `@allroles([])` evaluates to false — never admit
     * on an empty list, since an unguarded call would otherwise
     * render the protected block unconditionally.
     *
     * @return void
     */
    public function testAllRolesDirectiveRejectsEmptyList(): void
    {
        $user = StubIdentity::create(['id' => (string) Str::uuid()]);

        $this->actAs($user);

        $output = $this->render('@allroles([]) admitted @endallroles');

        self::assertSame('', $output);
    }

    /**
     * `@permission` admits when the principal holds the
     * permission via a direct grant.
     *
     * @return void
     */
    public function testPermissionDirectiveAdmitsDirectGrant(): void
    {
        Permission::create([
            'id'         => (string) Str::uuid(),
            'name'       => self::PERMISSION,
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->givePermission(self::PERMISSION);

        $this->actAs($user);

        $output = $this->render('@permission(\'' . self::PERMISSION . '\') yes @endpermission');

        self::assertSame('yes', $output);
    }

    /**
     * `@permission` admits a role-inherited grant — the helper
     * folds direct + role-derived permissions through
     * `hasPermission()`.
     *
     * @return void
     */
    public function testPermissionDirectiveAdmitsRoleInheritedGrant(): void
    {
        $permission = Permission::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'posts:publish',
            'guard_name' => 'web',
        ]);
        $role = Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'publisher',
            'guard_name' => 'web',
        ]);
        $role->permissions()->attach($permission->getKey());

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('publisher');

        $this->actAs($user);

        $output = $this->render('@permission(\'posts:publish\') yes @endpermission');

        self::assertSame('yes', $output);
    }

    /**
     * `@allpermissions` requires every permission in the list.
     *
     * @return void
     */
    public function testAllPermissionsDirectiveRequiresEveryPermission(): void
    {
        Permission::create([
            'id'         => (string) Str::uuid(),
            'name'       => self::PERMISSION,
            'guard_name' => 'web',
        ]);
        Permission::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'posts:delete',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->givePermission(self::PERMISSION);

        $this->actAs($user);

        $template = '@allpermissions([\'' . self::PERMISSION . '\', \'posts:delete\']) both @endallpermissions';

        self::assertSame('', $this->render($template));

        $user->givePermission('posts:delete');

        self::assertSame('both', $this->render($template));
    }

    /**
     * `@unlessrole` renders when the role is not held — closes
     * with the Spatie-shaped `@endunlessrole`.
     *
     * @return void
     */
    public function testUnlessRoleDirectiveRendersWhenRoleMissing(): void
    {
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'banned',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);

        $this->actAs($user);

        $output = $this->render('@unlessrole(\'banned\') welcome @endunlessrole');

        self::assertSame('welcome', $output);
    }

    /**
     * `@unlessrole` suppresses its body when the role is held.
     *
     * @return void
     */
    public function testUnlessRoleDirectiveSuppressesWhenRoleHeld(): void
    {
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'banned',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('banned');

        $this->actAs($user);

        $output = $this->render('@unlessrole(\'banned\') welcome @endunlessrole');

        self::assertSame('', $output);
    }

    /**
     * The `Blade::if`-generated `@endrole` closing tag also
     * closes a `@unlessrole` block — both idioms must compile.
     *
     * @return void
     */
    public function testUnlessRoleAcceptsEndRoleAsClosingTag(): void
    {
        Role::create([
            'id'         => (string) Str::uuid(),
            'name'       => 'banned',
            'guard_name' => 'web',
        ]);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);

        $this->actAs($user);

        $output = $this->render('@unlessrole(\'banned\') welcome @endrole');

        self::assertSame('welcome', $output);
    }

    /**
     * Every canonical and Spatie-compat directive registers a
     * matching `@endunless<name>` alias — a migrated Spatie view
     * that uses `@endunlesshasrole`, `@endunlesshasanyrole`,
     * `@endunlesshasallroles`, `@endunlesspermission`,
     * `@endunlessanypermission`, `@endunlessallpermissions`,
     * `@endunlesshaspermission`, `@endunlesshasanypermission`, or
     * `@endunlesshasallpermissions` compiles cleanly alongside
     * `@endunlessrole` (see issues #85, #86).
     *
     * @return void
     */
    public function testEveryUnlessVariantHasASpatieShapedClosingAlias(): void
    {
        Role::create(['id' => (string) Str::uuid(), 'name' => 'admin', 'guard_name' => 'web']);
        Permission::create(['id' => (string) Str::uuid(), 'name' => 'posts:draft', 'guard_name' => 'web']);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $this->actAs($user);

        $closings = [
            '@unlessrole(\'admin\') yes @endunlessrole',
            '@unlessanyrole([\'admin\']) yes @endunlessanyrole',
            '@unlessallroles([\'admin\']) yes @endunlessallroles',
            '@unlesshasrole(\'admin\') yes @endunlesshasrole',
            '@unlesshasanyrole([\'admin\']) yes @endunlesshasanyrole',
            '@unlesshasallroles([\'admin\']) yes @endunlesshasallroles',
            '@unlesspermission(\'posts:draft\') yes @endunlesspermission',
            '@unlessanypermission([\'posts:draft\']) yes @endunlessanypermission',
            '@unlessallpermissions([\'posts:draft\']) yes @endunlessallpermissions',
            '@unlesshaspermission(\'posts:draft\') yes @endunlesshaspermission',
            '@unlesshasanypermission([\'posts:draft\']) yes @endunlesshasanypermission',
            '@unlesshasallpermissions([\'posts:draft\']) yes @endunlesshasallpermissions',
        ];

        foreach ($closings as $template) {
            self::assertSame('yes', $this->render($template), "Failed template: {$template}");
        }
    }

    /**
     * `@hasrole`, `@hasanyrole`, `@hasallroles` are Spatie-compat
     * aliases — they must behave identically to their canonical
     * counterparts so a migrated view renders unchanged.
     *
     * @return void
     */
    public function testSpatieAliasesMatchCanonicalBehaviour(): void
    {
        Role::create(['id' => (string) Str::uuid(), 'name' => 'admin', 'guard_name' => 'web']);
        Role::create(['id' => (string) Str::uuid(), 'name' => 'editor', 'guard_name' => 'web']);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->assignRole('admin');

        $this->actAs($user);

        self::assertSame('yes', $this->render('@hasrole(\'admin\') yes @endhasrole'));
        self::assertSame('yes', $this->render('@hasanyrole([\'editor\', \'admin\']) yes @endhasanyrole'));
        self::assertSame('', $this->render('@hasallroles([\'admin\', \'editor\']) yes @endhasallroles'));

        $user->assignRole('editor');
        self::assertSame('yes', $this->render('@hasallroles([\'admin\', \'editor\']) yes @endhasallroles'));
    }

    /**
     * `@haspermission`, `@hasanypermission`, `@hasallpermissions`
     * are the permission-side Spatie-compat aliases — they must
     * behave identically to their canonical counterparts so a
     * migrated view renders unchanged (see issue #85).
     *
     * @return void
     */
    public function testSpatiePermissionAliasesMatchCanonicalBehaviour(): void
    {
        Permission::create(['id' => (string) Str::uuid(), 'name' => self::PERMISSION, 'guard_name' => 'web']);
        Permission::create(['id' => (string) Str::uuid(), 'name' => 'posts:delete', 'guard_name' => 'web']);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $user->givePermission(self::PERMISSION);

        $this->actAs($user);

        self::assertSame('yes', $this->render('@haspermission(\'' . self::PERMISSION . '\') yes @endhaspermission'));
        self::assertSame('yes', $this->render('@hasanypermission([\'posts:delete\', \'' . self::PERMISSION . '\']) yes @endhasanypermission'));
        self::assertSame('', $this->render('@hasallpermissions([\'' . self::PERMISSION . '\', \'posts:delete\']) yes @endhasallpermissions'));

        $user->givePermission('posts:delete');
        self::assertSame('yes', $this->render('@hasallpermissions([\'' . self::PERMISSION . '\', \'posts:delete\']) yes @endhasallpermissions'));
    }

    /**
     * `@unlesshaspermission` / `@unlesshasanypermission` /
     * `@unlesshasallpermissions` close with the Spatie-shaped
     * `@endunless<name>` directives. Anonymous principal evaluates
     * every predicate to false so the unless-bodies render.
     *
     * @return void
     */
    public function testSpatiePermissionUnlessAliasesCompileWithEndunless(): void
    {
        Permission::create(['id' => (string) Str::uuid(), 'name' => 'posts:draft', 'guard_name' => 'web']);

        $user = StubIdentity::create(['id' => (string) Str::uuid()]);
        $this->actAs($user);

        self::assertSame('yes', $this->render('@unlesshaspermission(\'posts:draft\') yes @endunlesshaspermission'));
        self::assertSame('yes', $this->render('@unlesshasanypermission([\'posts:draft\']) yes @endunlesshasanypermission'));
        self::assertSame('yes', $this->render('@unlesshasallpermissions([\'posts:draft\']) yes @endunlesshasallpermissions'));
    }

    /**
     * Empty-string arguments must never admit the block — an
     * accidental `@role('')` or typo-driven `@permission('')`
     * is rejected at the helper rather than treated as "match
     * everything".
     *
     * @return void
     */
    public function testEmptyStringArgumentDoesNotAdmit(): void
    {
        $user = StubIdentity::create(['id' => (string) Str::uuid()]);

        $this->actAs($user);

        self::assertSame('', $this->render('@role(\'\') admitted @endrole'));
        self::assertSame('', $this->render('@permission(\'\') admitted @endpermission'));
    }

    /**
     * Bind a principal resolver that returns the supplied user —
     * equivalent to `actingAs()` for the purposes of the view
     * layer, without needing an auth-provider backing.
     *
     * @param  object|null  $principal
     * @return void
     */
    private function actAs(?object $principal): void
    {
        $resolver = new class ($principal) implements PrincipalResolver {
            /**
             * @param  object|null  $principal
             */
            public function __construct(private readonly ?object $principal) {}

            /**
             * Return the principal bound on this scoped resolver.
             *
             * @return object|null
             */
            public function resolve(): ?object
            {
                return $this->principal;
            }
        };

        $this->app->instance(PrincipalResolver::class, $resolver); // @phpstan-ignore method.nonObject
    }

    /**
     * Render a template and strip surrounding whitespace so the
     * assertions read cleanly.
     *
     * @param  string  $template
     * @return string
     */
    private function render(string $template): string
    {
        return \trim(Blade::render($template));
    }
}
